version: '3'

services:

 clickhouse-server:
    image: clickhouse/clickhouse-server
    container_name: logs-clickhouse-server
    ports:
      - "18123:8123"
      - "19000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: always

 log-analysis-compose:
    image: 'docker-log-analysis:1'
    ports:
      - "8094:8094"
    depends_on:
      - clickhouse-server
    restart: always

 log-receiver-compose:
    image: 'docker-log-receiver:1'
    ports:
      - "50055:50055"
    restart: always

 log-ui-compose:
    image: 'docker-log-ui:1'
    ports:
      - "8095:8095"
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
